Importer = new Object();
Importer._scriptName = typeof(__IMPORTER__) == "undefined" ? "js/import.js" : "import.js";

// get script location of import.js
Importer._getScriptLocation = function() {
    var scriptLocation = "";
    var SCRIPT_NAME = Importer._scriptName;

    var scripts = document.getElementsByTagName('script');
    for(var i = 0; i < scripts.length; i++) {
        var src = scripts[i].getAttribute('src');
        if(src) {
            var index = src.lastIndexOf(SCRIPT_NAME);
            // is it found, at the end of the URL?
            if((index > -1) && (index + SCRIPT_NAME.length == src.length)) {
                scriptLocation = src.slice(0, -SCRIPT_NAME.length);
                break;
            }
        }
    }
    return scriptLocation;
}

/*
 The original code appeared to use a try/catch block
 to avoid polluting the global namespace,
 we now use a anonymous function to achieve the same result.
 */
var jsfiles = new Array(
	"sound/soundmanager2.js",
	"jquery-1.9.1.js",
	"gf/ext/_global.js",
	"gf/ext/_namespace.js",
	"gf/ext/_Type.js",
	"gf/ext/_jsfext_ajax.js",
	"gf/ext/_jsfext_canvas.js",
	"gf/ext/_jsfext_event.js",
	"gf/ext/_jsfext_init.js",
	"gf/ext/_jsfext_random.js",
	"gf/ext/_jsfext_sound.js",
	"gf/ext/_jsfext_util.js",
	"gf/ext/_jsfext_webgl.js",
	"gf/ext/Array.js",
	"gf/ext/ArrayEnumerator.js",
	"gf/ext/Boolean.js",
	"gf/ext/CancelEventArgs.js",
	"gf/ext/CollectionChangedEventArgs.js",
	"gf/ext/CultureInfo.js",
	"gf/ext/Date.js",
	"gf/ext/Debug.js",
	"gf/ext/Delegate.js",
	"gf/ext/Enum.js",
	"gf/ext/Error.js",
	"gf/ext/EventArgs.js",
	"gf/ext/IDisposable.js",
	"gf/ext/IEnumerable.js",
	"gf/ext/IEnumerator.js",
	"gf/ext/INotifyCollectionChanged.js",
	"gf/ext/INotifyPropertyChanged.js",
	"gf/ext/Number.js",
	"gf/ext/Object.js",
	"gf/ext/PropertyChangedEventArgs.js",
	"gf/ext/RegExp.js",
	"gf/ext/String.js",
	"gf/ext/StringBuilder.js",
	"gf/ext/XmlDocumentParser.js",
	"gf/ext/CollectionChangedAction.js",
	"gf/_namespace.js",
	"gf/BaseApp.js",
	"gf/CurvedVal.js",
	"gf/DataBuffer.js",
	"gf/DataBufferData.js",
	"gf/IDisposable.js",
	"gf/Insets.js",
	"gf/JSONFormatException.js",
	"gf/JSONHelperData.js",
	"gf/KeyCode.js",
	"gf/NoRename.js",
	"gf/Sprite.js",
	"gf/TArray.js",
	"gf/TDictionary.js",
	"gf/TDictionaryEnumerator.js",
	"gf/TIntDictionary.js",
	"gf/TIntMap.js",
	"gf/TIntRect.js",
	"gf/TIntVector.js",
	"gf/TMap.js",
	"gf/TMapEnumerator.js",
	"gf/TMapKeyEnumerator.js",
	"gf/TMapValueEnumerator.js",
	"gf/TRect.js",
	"gf/TVector.js",
	"gf/Utils.js",
	"gf/XMLParser.js",
	"gf/XMLParserList.js",
	"gf/ads/AdAPIEvent.js",
	"gf/connected/ConnectedRequest.js",
	"gf/connected/Database.js",
	"gf/connected/Facebook.js",
	"gf/connected/HTTPService.js",
	"gf/connected/SocialService.js",
	"gf/connected/UserInfo.js",
	"gf/events/Event.js",
	"gf/events/EventDispatcher.js",
	"gf/events/IOErrorEvent.js",
	"gf/geom/Axes3.js",
	"gf/geom/Coords3.js",
	"gf/geom/Matrix.js",
	"gf/geom/Matrix3D.js",
	"gf/geom/Quat3.js",
	"gf/geom/TIntPoint.js",
	"gf/geom/TPoint.js",
	"gf/geom/Vector3.js",
	"gf/gfx/Camera.js",
	"gf/gfx/Color.js",
	"gf/gfx/ETextOverflowMode.js",
	"gf/gfx/Graphics.js",
	"gf/gfx/Graphics3D.js",
	"gf/gfx/OffsetDrawable.js",
	"gf/gfx/PerspectiveCamera.js",
	"gf/gfx/TransformedDrawable.js",
	"gf/misc/Bezier.js",
	"gf/misc/BSpline.js",
	"gf/misc/CurveCacheRecord.js",
	"gf/misc/CurveValDataPoint.js",
	"gf/misc/DisposeProxy.js",
	"gf/misc/DisposeProxyStatic.js",
	"gf/misc/JSONString.js",
	"gf/misc/Key1.js",
	"gf/misc/KeyVal.js",
	"gf/misc/SexyMathHermite.js",
	"gf/misc/TMapSorter.js",
	"gf/resources/BaseRes.js",
	"gf/resources/FontCharData.js",
	"gf/resources/FontDrawCmd.js",
	"gf/resources/FontDrawData.js",
	"gf/resources/FontLayer.js",
	"gf/resources/FontResource.js",
	"gf/resources/ImageInst.js",
	"gf/resources/ImageResource.js",
	"gf/resources/MeshEvent.js",
	"gf/resources/MeshPiece.js",
	"gf/resources/MeshResource.js",
	"gf/resources/PIBlocker.js",
	"gf/resources/PIDeflector.js",
	"gf/resources/PIEffect.js",
	"gf/resources/PIEffectDef.js",
	"gf/resources/PIEmitter.js",
	"gf/resources/PIEmitterBase.js",
	"gf/resources/PIEmitterInstance.js",
	"gf/resources/PIEmitterInstanceDef.js",
	"gf/resources/PIForce.js",
	"gf/resources/PIFreeEmitterInstance.js",
	"gf/resources/PIGeomDataEx.js",
	"gf/resources/PIInterpolator.js",
	"gf/resources/PIInterpolatorPoint.js",
	"gf/resources/PILayer.js",
	"gf/resources/PILayerDef.js",
	"gf/resources/PILifeValueSample.js",
	"gf/resources/PILifeValueTable.js",
	"gf/resources/PIParticleDef.js",
	"gf/resources/PIParticleDefInstance.js",
	"gf/resources/PIParticleGroup.js",
	"gf/resources/PIParticleInstance.js",
	"gf/resources/PITexture.js",
	"gf/resources/PITextureChunk.js",
	"gf/resources/PIValue.js",
	"gf/resources/PIValue2D.js",
	"gf/resources/PIValuePoint.js",
	"gf/resources/PIValuePoint2D.js",
	"gf/resources/PixelSnapping.js",
	"gf/resources/PopAnimCalcObjectPosData.js",
	"gf/resources/PopAnimResource.js",
	"gf/resources/RenderEffect.js",
	"gf/resources/RenderEffectPass.js",
	"gf/resources/RenderEffectRunHandle.js",
	"gf/resources/ResourceManager.js",
	"gf/resources/ResourceStreamer.js",
	"gf/resources/SoundInstance.js",
	"gf/resources/SoundManager.js",
	"gf/resources/SoundResource.js",
	"gf/resources/popanim/PopAnimCommand.js",
	"gf/resources/popanim/PopAnimDef.js",
	"gf/resources/popanim/PopAnimEvent.js",
	"gf/resources/popanim/PopAnimFrame.js",
	"gf/resources/popanim/PopAnimImage.js",
	"gf/resources/popanim/PopAnimObjectDef.js",
	"gf/resources/popanim/PopAnimObjectInst.js",
	"gf/resources/popanim/PopAnimObjectPos.js",
	"gf/resources/popanim/PopAnimObjectPosData.js",
	"gf/resources/popanim/PopAnimParticleEffect.js",
	"gf/resources/popanim/PopAnimSpriteDef.js",
	"gf/resources/popanim/PopAnimSpriteInst.js",
	"gf/widgets/ButtonWidget.js",
	"gf/widgets/ClassicWidget.js",
	"gf/widgets/ClassicWidgetAppState.js",
	"gf/widgets/Dialog.js",
	"gf/widgets/DialogEvent.js",
	"gf/widgets/EditWidget.js",
	"gf/widgets/WidgetEvent.js",
	"gf/widgets/WidthCheckEntry.js",
	"gf/gfx/TriVertex.js",
	"jsgf/JSBaseApp.js",
	"jsgf/JSDataBufferData.js",
	"jsgf/gfx/JSGraphics.js",
	"jsgf/gfx/JSGraphics3D.js",
	"jsgf/resources/JSImageInst.js",
	"jsgf/resources/JSImageResource.js",
	"jsgf/resources/JSMeshPiece.js",
	"jsgf/resources/JSMeshResource.js",
	"jsgf/resources/JSRenderEffect.js",
	"jsgf/resources/JSRenderEffectBlock.js",
	"jsgf/resources/JSRenderEffectPass.js",
	"jsgf/resources/JSRenderEffectRunHandle.js",
	"jsgf/resources/JSRenderEffectTechnique.js",
	"jsgf/resources/JSResourceManager.js",
	"jsgf/resources/JSSoundInstance.js",
	"jsgf/resources/JSSoundResource.js",
	"game/_namespace.js",
	"game/Announcement.js",
	"game/Background.js",
	"game/BackgroundLoader.js",
	"game/BarInstance.js",
	"game/Bej3Button.js",
	"game/Bej3Dialog.js",
	"game/Bej3DialogButton.js",
	"game/Bej3EditWidget.js",
	"game/BejApp.js",
	"game/BejUtil.js",
	"game/Board.js",
	"game/BoardInfo.js",
	"game/Checkbox.js",
	"game/CheckMatrixInfo.js",
	"game/ClassicBoard.js",
	"game/ClassicEndLevelDialog.js",
	"game/ColorCycle.js",
	"game/ColorTracker.js",
	"game/CrystalBall.js",
	"game/CurvedAlphaButton.js",
	"game/CurvedValTable.js",
	"game/DeferredSound.js",
	"game/DeferredTutorial.js",
	"game/DialogMgr.js",
	"game/DistortionQuad.js",
	"game/DM.js",
	"game/Effect.js",
	"game/EffectsManager.js",
	"game/ElectroBolt.js",
	"game/ElectrocutedCel.js",
	"game/EndLevelDialog.js",
	"game/FrameButton.js",
	"game/GemInfo.js",
	"game/GemOutlines.js",
	"game/GfxUtil.js",
	"game/GlobalMembersEndLevelDialog.js",
	"game/GlobalMembersHighScoreMgr.js",
	"game/GridData.js",
	"game/GridTileData.js",
	"game/HighScoreEntry.js",
	"game/HighScoreMgr.js",
	"game/HighScoreTable.js",
	"game/HintDialog.js",
	"game/HyperAnimKey.js",
	"game/HyperAnimSequence.js",
	"game/HyperMaterial.js",
	"game/Hyperspace.js",
	"game/HyperspaceFallback.js",
	"game/HyperspaceUltra.js",
	"game/IconButton.js",
	"game/Lightning.js",
	"game/LightningBarFillEffect.js",
	"game/LightningStorm.js",
	"game/LightningZap.js",
	"game/LoadingError.js",
	"game/LoadingScreen.js",
	"game/MainMenu.js",
	"game/MatchSet.js",
	"game/MathUtil.js",
	"game/Messager.js",
	"game/MessagerMsg.js",
	"game/Metrics.js",
	"game/MoveData.js",
	"game/MTRand.js",
	"game/MusicInterface.js",
	"game/OptionsDialog.js",
	"game/ParticleEffect.js",
	"game/PartnerLogo.js",
	"game/Piece.js",
	"game/PieceIter.js",
	"game/Points.js",
	"game/PointsManager.js",
	"game/PopAnimEffect.js",
	"game/Profile.js",
	"game/QuasiRandom.js",
	"game/QueuedMove.js",
	"game/RankBarWidget.js",
	"game/RankUpDialog.js",
	"game/RecordsDialog.js",
	"game/ResourceCache.js",
	"game/Resources.js",
	"game/ScalingIconButton.js",
	"game/Slider.js",
	"game/SoundUtil.js",
	"game/Span.js",
	"game/SpanRow.js",
	"game/SpeedBoard.js",
	"game/SpeedCollectEffect.js",
	"game/SpeedEndLevelDialog.js",
	"game/SpreadCurve.js",
	"game/StateInfo.js",
	"game/SwapData.js",
	"game/TextButton.js",
	"game/TextNotifyEffect.js",
	"game/TimeBonusEffect.js",
	"game/TimeBonusEffectTop.js",
	"game/Tooltip.js",
	"game/TooltipManager.js",
	"game/TopWidget.js",
	"game/TutorialMgr.js",
	"game/TutorialSequence.js",
	"game/TutorialStep.js",
	"game/Util.js",
	"game/Version.js",
	"main.js"
);
if(typeof(__IMPORTER__) == "undefined") {
	(function() {

        var allScriptTags = "";
        var host = Importer._getScriptLocation() + "js/";

        for(var i = 0; i < jsfiles.length; i++) {
            if(/MSIE/.test(navigator.userAgent) || /Safari/.test(navigator.userAgent)) {
                var currentScriptTag = "<script src='" + host + jsfiles[i] + "'></script>";
                allScriptTags += currentScriptTag;
            } else {
                var s = document.createElement("script");
                s.src = host + jsfiles[i];
                var h = document.getElementsByTagName("body").length ? document.getElementsByTagName("body")[0] : document.body;
                h.appendChild(s);
            }
        }
        if(allScriptTags) {
            document.write(allScriptTags);
        }
    })();
}